ARG PNAME="next-tmpl"

# build stage
FROM ${PNAME}:base AS build

COPY package.json package-lock.json /project/

WORKDIR /project

RUN --mount=type=cache,target=/root/.npm set -eux; \
    npm config set registry https://registry.npmmirror.com ; \
    npm install

COPY . /project

RUN set -eux; \
    sed -i "s@standalone@export@g" next.config.ts; \
    npm run build


# deploy stage
FROM nginx:1.26-alpine AS runner
COPY --from=build /project/out /usr/share/nginx/html
