ARG PNAME="next-tmpl"

FROM ${PNAME}:base

RUN --mount=type=cache,target=/var/cache/apk/ set -eux; \
    apk add curl git g++ gcc make ; \
    npm install -g pnpm

RUN --mount=type=cache,target=/var/cache/apk/ set -eux; \
    apk add bash openssh-client-default

COPY --chmod=755 docker/postcreate.dev /postcreate

USER node
