ARG PNAME="rust-tmpl"

FROM ${PNAME}:base

RUN --mount=type=cache,target=/var/cache/apk/ set -eux; \
    addgroup -g 1000 rust; \
    adduser -u 1000 -G rust -s /bin/sh -D rust \
    ; \
    apk add bash openssh-client-default

COPY --chmod=755 docker/postcreate /postcreate

USER rust
