ARG PNAME="rust-tmpl"

# build stage
FROM ${PNAME}:base AS build

COPY . /project

WORKDIR /project

RUN --mount=type=cache,target=/project/target/ \
    --mount=type=cache,target=/usr/local/cargo/git/db \
    --mount=type=cache,target=/usr/local/cargo/registry/ \
    set -eux; \
    cargo install --root /opt/project --path .


# deploy stage
FROM alpine:3

COPY --from=build /opt/project /opt/project

ENV PATH="${PATH}:/opt/project/bin"
