ARG PNAME="python-tmpl"

FROM ${PNAME}:base

RUN --mount=type=cache,target=/var/cache/apk/ set -eux; \
    apk add curl git g++ gcc make \
        postgresql-dev

RUN --mount=type=cache,target=/var/cache/apk/ set -eux; \
    addgroup -g 1000 python; \
    adduser -u 1000 -G python -s /bin/sh -D python ;\
    apk add bash openssh-client-default

USER python
