FROM python:3.12-alpine

RUN --mount=type=cache,target=/var/cache/apk/ set -eux; \
    sed -i "s@dl-cdn.alpinelinux.org@mirrors.ustc.edu.cn@g" /etc/apk/repositories; \
    apk add curl git g++ gcc make
