FROM alpine:3

ENV VCPKG_FORCE_SYSTEM_BINARIES=1 \
    VCPKG_ROOT=/usr/local/vcpkg \
    VCPKG_COMMIT_ID=10b7a178346f3f0abef60cecd5130e295afd8da4 \
    VCPKG_TAG=2024.10.21 \
    PATH="${PATH}:/usr/local/vcpkg"

COPY --chmod=755 install-vcpkg /tmp/install-vcpkg

RUN --mount=type=cache,target=/var/cache/apk/ \
    set -eux; \
    apk add curl git g++ gcc make cmake ninja pkgconf zip unzip tar; \
    /tmp/install-vcpkg
