#!/bin/sh -e

mkdir -p "${VCPKG_ROOT}"

git clone --depth=1 -b ${VCPKG_TAG} https://github.com/microsoft/vcpkg "${VCPKG_ROOT}"

"${VCPKG_ROOT}/bootstrap-vcpkg.sh" -disableMetrics

rm -rf "${VCPKG_ROOT}/buildtrees/_vcpkg"
