ARG PNAME="maven-tmpl"

FROM ${PNAME}:base AS build

RUN --mount=type=cache,target=/var/cache/apk/ set -eux; \
    addgroup -g 1000 java; \
    adduser -u 1000 -G java -s /bin/sh -D java \
    ; \
    apk add bash openssh-client-default

COPY --chmod=755 docker/postcreate.dev /postcreate

USER java
